version: '3'

services:
  app:
    build: .
    container_name: pmsf-wam-app
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    container_name: pmsf-wam-mongodb
    image: mongo:latest
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
      - MONGO_INITDB_DATABASE=pmsf-wam
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
