version: '3'

services:
  mongodb:
    container_name: pmsf-wam-mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
      - MONGO_INITDB_DATABASE=pmsf-wam
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: